# Pull base image
# ---------------
FROM oracle/database:11.2.0.2-xe

# Maintainer
# ----------
MAINTAINER Bill Waters <wjwaters2@gaig.com>

ENV ORACLE_PWD=4dminPass

COPY scripts/*.sh $ORACLE_BASE/

# Builds Oracle DB inside of this image
RUN $ORACLE_BASE/runOracle.sh

# Starts Oracle DB and creates users based on environment variables
CMD $ORACLE_BASE/entrypoint.sh
